- name: install and configure nginx
  hosts: target_servers
  become: True
  vars:
   NGINX_CONF: /etc/nginx/conf.d/default.conf
   SRC_NGINX_CONF: config/my.j2
   SVC_NAME: nginx
   NGINX_PORT: 80
   URL: https://www.google.com
  tasks:
    - name: Add nginx repository
      yum_repository:
       name: epel
       description: NGINX
       baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
       gpgcheck: no

    - name: install nginx
      yum:
       name: nginx
       state: present
    - name: copy nginx server.crt file
      copy:
       src: ssl/server.crt 
       dest: /etc/nginx/server.crt
       force: yes
    - name: copy nginx server.key file
      copy:
       src: ssl/server.key
       dest: /etc/nginx/server.key
       force: yes
    - name: copy nginx config file
      template:
       src: "{{SRC_NGINX_CONF}}"
       dest: "{{NGINX_CONF}}"
       force: yes
    - name: URI
      uri:
        url: "{{URL}}"
        return_content: yes
      register: website_content
    - name: show website_content
      debug:
        var: website_content
    - name: copy nginx contents
      template:
       src: content/index.j2
       dest: /usr/share/nginx/html/index.html
       force: yes

    - name: start nginx service
      service:
       name: "{{SVC_NAME }}"
       state: restarted





